### ISSUE TITLE
Android & AndroidX package merge

### ISSUE THREAD

**Issue by arnaudgiuliani** [uniflow-kt/uniflow-kt#52]
Hi All 👋

the "old" Android support package will be deprecated for end of year. I propose to merge both `uniflow-android` & `uniflow-androidx` packages.

Which name do we keep then? 
- `uniflow-android`
- `uniflow-androidx`

I would propose to keep `uniflow-android` naming, and merge the AndroidX package inside.

**Comment by erikhuizinga** [comment]
I prefer the `uniflow-android` name, but `uniflow-androidx` has been downloaded over 3.3 times more often than `uniflow-android`: [source 1](https://bintray.com/uniflow/uniflow/uniflow-android#statistics), [source 2](https://bintray.com/uniflow/uniflow/uniflow-androidx#statistics).

Therefore I suggest to deprecate `uniflow-androidx` and notify users that build using that artifact that they should simply use `uniflow-android` instead. Or, if that's too much hassle and because this lib hasn't reached its stable v1 API yet, just go ahead and drop `uniflow-androidx` in favour of `uniflow-android`. Make sure to be very explicit about this in the readme and in the upcoming release notes (changelog, GitHub releases, etc.).

**Comment by arnaudgiuliani** [comment]
Yes interesting to see the usage. I will have the same problem with Koin, merging android & androidx project. One side will be some communication. Faking androidx package with android content just keep the problem for a time.

**Comment by arnaudgiuliani** [comment]
Next version to be published will be `1.0.0` - https://search.maven.org/search?q=org.uniflow-kt

uniflow-androidx has been merged into  uniflow-android
